[pyprland]
include = [
    "~/.config/pypr/pyprland.d",
]
plugins = [
    "expose",
    "fetch_client_menu",
    "gamemode",
    "lost_windows",
    "magnify",
    "menubar",
    "shift_monitors",
    "shift_monitors",
    "toggle_dpms",
    "toggle_special",
    "toggle_special",
    "workspaces_follow_focus",
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

[menubar]
command = "uwsm-app -- ashell"
monitors = [
    "eDP-1",
    "DP-1",
    "HDMI-A-1",
]

